services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
  backend:
    container_name: backend
    build:
      context: ./file-bucket-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    entrypoint:
      SPRING_DATASOURCE_URL:
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
      SPRING_FLYWAY_baselineOnMigrate:
      SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE:
      VIRUS-TOTAL_API-KEY:
      AWS_S3_BUCKET:
      TOKEN_SIGNING_KEY: