spring:
  datasource:
    url:
    username:
    password:
  flyway:
    baselineOnMigrate: true
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
virustotal:
  api-key:
aws:
  s3:
    key:
    secret:
    bucket: