spring:
  datasource:
    url:
    username:
    password:
  flyway:
    baselineOnMigrate: true
  servlet:
    multipart:
      max-file-size: 1000MB
virus-total:
  api-key:
aws:
  s3:
    key:
    secret:
    bucket:
token:
  signing:
    key:
