POST /api/v3/files HTTP/1.1
Accept: application/json
X-Apikey: <virustotal API key>
Content-Type: multipart/form-data;
Host: www.virustotal.com
Content-Length: 625

###

GET https://www.virustotal.com/api/v3/analyses/ZTY5MTE3YThmM2Q0ZWExYjI2M2E4NzA3NjZmMzZiOTk6MTcwMzY5NTUwMQ== HTTP/1.1
Accept: application/json
X-Apikey:  <virustotal API key>
